<<<<<<< HEAD
name: ecommerce_store
description: تطبيق متجر إلكتروني باستخدام Flutter و Firebase
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
=======
name: dz_shoping
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1
>>>>>>> 7bee6cb7fb3f02d97e350d9f59ea00a13815abfa

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD

  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_messaging: ^14.7.14
  firebase_storage: ^11.7.4
  flutter_local_notifications: ^17.1.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.5
  flutter_localizations:
    sdk: flutter
=======
  cupertino_icons: ^1.0.8
>>>>>>> 7bee6cb7fb3f02d97e350d9f59ea00a13815abfa

dev_dependencies:
  flutter_test:
    sdk: flutter
<<<<<<< HEAD
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/
=======
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg.jpg
>>>>>>> 7bee6cb7fb3f02d97e350d9f59ea00a13815abfa
